# JSON Schema for metadata/*.yaml files
# This schema defines the structure for plot metadata

$schema: "http://json-schema.org/draft-07/schema#"
title: Plot Metadata
description: Metadata for a plot specification including tags, implementations, and history
type: object

required:
  - spec_id
  - title
  - tags
  - implementations

properties:
  spec_id:
    type: string
    description: Unique identifier matching the spec filename (e.g., scatter-basic)
    pattern: "^[a-z][a-z0-9-]*$"

  title:
    type: string
    description: Human-readable title of the plot

  tags:
    type: object
    description: Categorization tags (same for all library implementations)
    properties:
      plot_type:
        type: array
        items:
          type: string
        description: "Type of visualization (e.g., scatter, bar, line, heatmap)"
      domain:
        type: array
        items:
          type: string
        description: "Application domains (e.g., statistics, finance, science)"
      features:
        type: array
        items:
          type: string
        description: "Plot features (e.g., basic, 2d, interactive, animated)"
      audience:
        type: array
        items:
          type: string
        description: "Target audience (e.g., beginner, intermediate, advanced)"
      data_type:
        type: array
        items:
          type: string
        description: "Data types used (e.g., numeric, categorical, temporal)"

  implementations:
    type: object
    description: Per-library implementation metadata
    additionalProperties:
      $ref: "#/definitions/implementation"

definitions:
  implementation:
    type: object
    required:
      - plot_function
      - variant
      - file_path
    properties:
      plot_function:
        type: string
        description: Library-specific plot function name (e.g., scatter, scatterplot)

      variant:
        type: string
        description: Implementation variant (default, ggplot_style, etc.)
        default: default

      file_path:
        type: string
        description: Relative path to the implementation file

      preview_url:
        type: string
        format: uri
        description: URL to the preview image in GCS

      current:
        $ref: "#/definitions/generation_info"
        description: Current implementation details

      history:
        type: array
        items:
          $ref: "#/definitions/history_entry"
        description: Previous implementation attempts and versions

  generation_info:
    type: object
    properties:
      generated_at:
        type: string
        format: date-time
        description: ISO 8601 timestamp when code was generated

      generated_by:
        type: string
        description: Model ID that generated the code (e.g., claude-opus-4-5-20251101)

      workflow_run:
        type: integer
        description: GitHub Actions workflow run ID

      issue:
        type: integer
        description: GitHub Issue number that triggered generation

      quality_score:
        type: number
        minimum: 0
        maximum: 100
        description: Overall quality score (0-100)

  history_entry:
    type: object
    required:
      - version
      - generated_at
    properties:
      version:
        type: integer
        description: Version number (1, 2, 3, ...)

      generated_at:
        type: string
        format: date-time

      generated_by:
        type: string

      workflow_run:
        type: integer

      quality_score:
        type: number
        minimum: 0
        maximum: 100

      feedback:
        type: string
        description: Quality evaluation feedback

      improvements_suggested:
        type: array
        items:
          type: string
        description: Suggested improvements for next iteration

      evaluators:
        type: array
        items:
          type: object
          properties:
            model:
              type: string
            score:
              type: number
        description: Individual evaluator scores

      status:
        type: string
        enum: [superseded, rejected, not-feasible]
        description: Status of this historical version
