name: Plot Request
description: Propose a new plot type for pyplots
title: "Plot: "
labels: ["plot-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## New Plot Proposal

        Describe the plot you'd like to see. Our AI will:
        1. Check for similar existing plots
        2. Assign a descriptive spec ID (e.g., `scatter-regression-linear`)
        3. Create the specification for review

        **After submission:** A maintainer will review and add the `approved` label to start code generation.

  - type: textarea
    id: description
    attributes:
      label: What should this plot show?
      description: Describe the visualization you need (1-3 sentences)
      placeholder: "A scatter plot with a linear regression line that shows the correlation between two variables, including confidence intervals."
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases (optional)
      description: When would someone use this plot?
      placeholder: |
        - Analyzing relationship between marketing spend and sales
        - Visualizing correlation in scientific experiments
    validations:
      required: false

  - type: dropdown
    id: plot_type
    attributes:
      label: Plot Type
      description: What type of visualization is this?
      options:
        - scatter
        - line
        - bar
        - histogram
        - heatmap
        - box
        - violin
        - pie
        - area
        - other
    validations:
      required: false

  - type: checkboxes
    id: features
    attributes:
      label: Features (optional)
      description: Select any special features you'd like
      options:
        - label: grouped
        - label: stacked
        - label: horizontal
        - label: animated
        - label: interactive
        - label: 3d
        - label: regression
        - label: annotations
