name: Plot Update
description: Request updates or regeneration of an existing plot
title: "[spec-id] [update] "
labels: ["plot-request", "update"]
body:
  - type: markdown
    attributes:
      value: |
        ## Plot Update Request

        Use this form to update or regenerate an existing plot.

        **Title Format:**
        - `[scatter-basic] [update] Regenerate` → Regenerate all 9 libraries
        - `[scatter-basic] [update:seaborn] Fix colors` → Regenerate only seaborn

        Replace `[spec-id]` in the title with the actual spec ID (e.g., `scatter-basic`).

        After submitting, a maintainer will add the `approved` label to trigger regeneration.

  - type: dropdown
    id: target_library
    attributes:
      label: Target Library (optional)
      description: Update only a specific library, or leave empty for all. If you select a specific library, change [update] to [update:library] in the title.
      options:
        - All libraries
        - matplotlib
        - seaborn
        - plotly
        - bokeh
        - altair
        - plotnine
        - pygal
        - highcharts
        - letsplot
    validations:
      required: false

  - type: dropdown
    id: update_type
    attributes:
      label: Type of Update
      description: What kind of change is this?
      options:
        - Regenerate (use current spec with new code style)
        - Spec Update (describe changes below)
        - Bug Fix (plot doesn't render correctly)
        - Visual Improvement (styling, colors, layout)
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Requested Changes
      description: Describe the changes to the spec or implementation (Claude will update the spec first if needed)
      placeholder: |
        - Add grid lines for better readability
        - Change default color scheme to colorblind-friendly
        - Include legend for all data series
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (optional)
      description: Screenshots, code snippets, or other relevant information
    validations:
      required: false
