name: Plot Request
description: Propose a new plot type for pyplots
title: "[spec-id]: "
labels: ["plot-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Plot-Vorschlag
        Beschreibe kurz, welchen Plot du dir wünschst. Die AI generiert daraus eine vollständige Spezifikation.

        **Titel-Format:** `scatter-basic-001: Deine Kurzbeschreibung`

  - type: textarea
    id: description
    attributes:
      label: Was soll der Plot zeigen?
      description: 1-2 Sätze reichen
      placeholder: "Ein Scatter-Plot mit Regressionslinie, der Korrelationen zwischen zwei Variablen visualisiert."
    validations:
      required: true
