name: Plot Update
description: Request updates or regeneration of an existing plot
title: "[update] "
labels: ["plot-request", "update"]
body:
  - type: markdown
    attributes:
      value: |
        ## Plot Update Request

        Use this form to update or regenerate an existing plot.

        **Title Format:**
        - `[update] scatter-basic` → Regenerate all 8 libraries
        - `[update:seaborn] scatter-basic` → Regenerate only seaborn

        After submitting, a maintainer will add the `approved` label to trigger regeneration.

  - type: input
    id: spec_id
    attributes:
      label: Spec ID
      description: "The spec ID of the plot to update (will be appended to title)"
      placeholder: "scatter-basic"
    validations:
      required: true

  - type: dropdown
    id: target_library
    attributes:
      label: Target Library (optional)
      description: Update only a specific library, or leave empty for all
      options:
        - All libraries
        - matplotlib
        - seaborn
        - plotly
        - bokeh
        - altair
        - plotnine
        - pygal
        - highcharts
    validations:
      required: false

  - type: dropdown
    id: update_type
    attributes:
      label: Type of Update
      description: What kind of change is this?
      options:
        - Regenerate (use current spec)
        - Spec Update (describe changes below)
        - Bug Fix (plot doesn't render correctly)
        - Visual Improvement (styling, colors, layout)
        - Feature Addition (new parameter, option)
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Requested Changes
      description: Describe the changes to the spec or implementation (Claude will update the spec first if needed)
      placeholder: |
        - Add grid lines for better readability
        - Change default color scheme to colorblind-friendly
        - Include legend for all data series
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (optional)
      description: Screenshots, code snippets, or other relevant information
    validations:
      required: false
