name: Plot Update
description: Request updates or regeneration of an existing plot
title: "[SPEC-ID] [update] "
labels: ["spec-update"]
body:
  - type: markdown
    attributes:
      value: |
        ## Plot Update Request

        Use this to update or regenerate an existing plot.

        **Important:** Replace `SPEC-ID` in the title with the actual spec ID!

        **Title Examples:**
        - `[scatter-basic] [update] Regenerate all` - All 9 libraries
        - `[scatter-basic] [update:seaborn] Fix colors` - Only seaborn

        **After submission:** A maintainer will review and add the `approved` label to start regeneration.

  - type: input
    id: spec_id
    attributes:
      label: Spec ID
      description: "The spec ID to update (e.g., scatter-basic). Must match the title!"
      placeholder: "scatter-basic"
    validations:
      required: true

  - type: dropdown
    id: target_library
    attributes:
      label: Target Library
      description: "Update specific library or all? If specific, change [update] to [update:library] in title."
      options:
        - All libraries
        - matplotlib
        - seaborn
        - plotly
        - bokeh
        - altair
        - plotnine
        - pygal
        - highcharts
        - letsplot
    validations:
      required: true

  - type: dropdown
    id: update_type
    attributes:
      label: Type of Update
      description: What kind of change is this?
      options:
        - Regenerate (use current spec with new code style)
        - Spec Update (describe changes below)
        - Bug Fix (plot doesn't render correctly)
        - Visual Improvement (styling, colors, layout)
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Requested Changes
      description: Describe the changes to the spec or implementation
      placeholder: |
        - Add grid lines for better readability
        - Change default color scheme to colorblind-friendly
        - Include legend for all data series
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (optional)
      description: Screenshots, code snippets, or other relevant information
    validations:
      required: false
