name: Request Specification
description: Propose a new plot type for pyplots
labels: ["spec-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## New Plot Proposal

        Describe the plot you'd like to see. Our AI will:
        1. Check for similar existing plots
        2. Assign a spec ID (e.g., `scatter-regression-linear`)
        3. Create the specification for review

        **After submission:** A maintainer will review and add the `approved` label to start code generation.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What does this plot visualize? When should you use it? (2-4 sentences)
      placeholder: "A scatter plot with a linear regression line that shows the correlation between two variables. Useful for identifying trends and making predictions based on the relationship between variables."
    validations:
      required: true

  - type: textarea
    id: applications
    attributes:
      label: Applications
      description: Realistic scenarios where this plot would be used (with domain context)
      placeholder: |
        - Analyzing relationship between marketing spend and sales revenue
        - Visualizing correlation in scientific experiments
        - Predicting house prices based on square footage
    validations:
      required: false

  - type: textarea
    id: data
    attributes:
      label: Data
      description: What data does this plot need? (columns, types, size)
      placeholder: |
        - `x` (numeric) - independent variable
        - `y` (numeric) - dependent variable
        - Size: 50-500 points
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Optional implementation hints or special requirements
      placeholder: |
        - Show confidence interval band
        - Display R² value in legend
    validations:
      required: false
