"""initial_schema

Revision ID: 393d66bd73d9
Revises: 
Create Date: 2025-12-11 23:37:27.851407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '393d66bd73d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('documentation_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applications', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('data', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('issue', sa.Integer(), nullable=True),
    sa.Column('suggested', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implementations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('spec_id', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('preview_thumb', sa.String(), nullable=True),
    sa.Column('preview_html', sa.String(), nullable=True),
    sa.Column('python_version', sa.String(), nullable=True),
    sa.Column('library_version', sa.String(), nullable=True),
    sa.Column('tested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('issue', sa.Integer(), nullable=True),
    sa.Column('workflow_run', sa.BigInteger(), nullable=True),
    sa.Column('evaluator_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_feedback', sa.Text(), nullable=True),
    sa.Column('improvements_suggested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_id'], ['specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_id', 'library_id', name='uq_spec_library')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('implementations')
    op.drop_table('specs')
    op.drop_table('libraries')
    # ### end Alembic commands ###
