"""add_description_to_libraries

Revision ID: b26e9f4b532d
Revises: 6a8ae95eaf56
Create Date: 2025-12-17 21:56:35.415221

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b26e9f4b532d"
down_revision: Union[str, None] = "6a8ae95eaf56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("libraries", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("libraries", "description")
    # ### end Alembic commands ###
