"""Open the regen implementation PR.

Replaces regen.md step 2j (~70 lines of bash). Orchestrates:

1. Fetch `origin/main` and create a fresh worktree based on it
2. Copy the regenerated impl + metadata into the worktree
3. Commit + push + `gh pr create` with the **Parent Issue:** marker that
   `impl-merge.yml` parses to comment on the spec issue + add `impl:{lib}:done`
4. Add `quality:{score}` and `ai-approved`/`quality-poor` labels via
   the GitHub REST API (gh CLI label add is flaky on this repo because
   GraphQL warns about deprecated classic projects and aborts the mutation;
   REST is reliable)
5. Cleanup: remove the worktree and prune

Returns `(pr_url, pr_number)`.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import yaml

from . import QualityEval


@dataclass(frozen=True)
class PRResult:
    pr_url: str
    pr_number: int
    branch: str


# ---------------------------------------------------------------------------
# Git / GitHub helpers
# ---------------------------------------------------------------------------


def _read_spec_issue(spec_id: str, plots_root: Path = Path("plots")) -> int | None:
    spec_yaml = plots_root / spec_id / "specification.yaml"
    if not spec_yaml.is_file():
        return None
    try:
        data = yaml.safe_load(spec_yaml.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return None
    issue = data.get("issue")
    return int(issue) if issue else None


def _quality_label(score: int) -> str:
    """`quality:{score}` — matches what `impl-generate.yml` writes and
    `impl-merge.yml` reads. (Note: `automation/scripts/label_manager.py`
    has a separate categorical `get_quality_label` returning `quality:good`
    etc., used for issue tracking — different label space.)"""
    return f"quality:{int(score)}"


def _approval_label(score: int) -> str:
    return "ai-approved" if score >= 50 else "quality-poor"


def _build_pr_body(spec_id: str, library: str, quality: QualityEval, parent_issue: int | None) -> str:
    parent_line = f"**Parent Issue:** #{parent_issue}\n\n" if parent_issue else ""
    return (
        f"Locally regenerated **{library}** for **{spec_id}**.\n\n"
        f"Quality: {quality.score}/100\n"
        f"- {quality.category_breakdown()}\n\n"
        f"{parent_line}"
        "Generated by `/regen` (local model, no Cloud AI review dispatched)."
    )


def _repo_owner_name() -> tuple[str, str]:
    """Resolve `OWNER/REPO` from the current git remote (works for any clone)."""
    out = subprocess.check_output(["gh", "repo", "view", "--json", "owner,name"], text=True)
    j = json.loads(out)
    return j["owner"]["login"], j["name"]


def _add_labels(pr_number: int, labels: list[str]) -> None:
    """REST-based label add (avoids the gh GraphQL deprecation warning)."""
    owner, repo = _repo_owner_name()
    args = ["gh", "api", "-X", "POST", f"repos/{owner}/{repo}/issues/{pr_number}/labels"]
    for label in labels:
        args.extend(["-f", f"labels[]={label}"])
    subprocess.run(args, check=True)


# ---------------------------------------------------------------------------
# Main entrypoint
# ---------------------------------------------------------------------------


def create_regen_pr(
    spec_id: str,
    library: str,
    quality: QualityEval,
    plots_root: Path = Path("plots"),
    worktrees_root: Path = Path(".worktrees"),
) -> PRResult:
    branch = f"implementation/{spec_id}/{library}"
    worktree = worktrees_root / f"{spec_id}-{library}"

    # Fetch and (re-)create the worktree from current origin/main.
    # Also wipe any local branch from a previous attempt — `git worktree add -b`
    # would otherwise fail with "branch already exists" on a retry, so the
    # whole flow would not be idempotent.
    subprocess.run(["git", "fetch", "origin", "main"], check=True)
    if worktree.exists():
        subprocess.run(["git", "worktree", "remove", str(worktree), "--force"], check=False)
        subprocess.run(["git", "worktree", "prune"], check=False)
    subprocess.run(["git", "branch", "-D", branch], check=False, capture_output=True)
    subprocess.run(["git", "worktree", "add", "-b", branch, str(worktree), "origin/main"], check=True)

    try:
        # Copy the regenerated files into the worktree (impl + metadata at minimum)
        for rel in (
            f"plots/{spec_id}/implementations/python/{library}.py",
            f"plots/{spec_id}/metadata/python/{library}.yaml",
        ):
            src = Path(rel)
            dst = worktree / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, dst)

        # Commit, push, PR
        subprocess.run(["git", "-C", str(worktree), "add", "--", *_relative_files(spec_id, library)], check=True)
        subprocess.run(["git", "-C", str(worktree), "commit", "-m", f"regen({spec_id}): {library}"], check=True)
        subprocess.run(["git", "-C", str(worktree), "push", "-u", "origin", branch], check=True)

        parent_issue = _read_spec_issue(spec_id, plots_root)
        body = _build_pr_body(spec_id, library, quality, parent_issue)
        out = subprocess.check_output(
            [
                "gh",
                "pr",
                "create",
                "--title",
                f"regen({spec_id}): {library}",
                "--body",
                body,
                "--head",
                branch,
                "--base",
                "main",
            ],
            text=True,
            cwd=worktree,
        ).strip()
        pr_url = out.splitlines()[-1]  # last line is the PR URL
        pr_number = int(pr_url.rsplit("/", 1)[-1])

        # Label via REST (gh pr edit --add-label is flaky on this repo)
        _add_labels(pr_number, [_quality_label(quality.score), _approval_label(quality.score)])
    finally:
        # Always clean up the worktree AND the local branch — leaving the
        # branch behind would block the next regen attempt for this library.
        # The branch lives on the remote anyway after `git push`.
        if worktree.exists():
            subprocess.run(["git", "worktree", "remove", str(worktree), "--force"], check=False)
        subprocess.run(["git", "worktree", "prune"], check=False)
        subprocess.run(["git", "branch", "-D", branch], check=False, capture_output=True)

    return PRResult(pr_url=pr_url, pr_number=pr_number, branch=branch)


def _relative_files(spec_id: str, library: str) -> list[str]:
    return [f"plots/{spec_id}/implementations/python/{library}.py", f"plots/{spec_id}/metadata/python/{library}.yaml"]
