# Cloud Build configuration for pyplots Backend API
substitutions:
  _SERVICE_NAME: pyplots-backend
  _REGION: europe-west4
  _MEMORY: 512Mi
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "3"

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"
      - "-f"
      - "api/Dockerfile"
      - "."
    id: "build-image"

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID"
    id: "push-image"
    waitFor: ["build-image"]

  # Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"
    id: "push-latest"
    waitFor: ["build-image"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--memory=${_MEMORY}"
      - "--min-instances=${_MIN_INSTANCES}"
      - "--max-instances=${_MAX_INSTANCES}"
      - "--port=8000"
      - "--allow-unauthenticated"
      - "--add-cloudsql-instances=pyplots:europe-west4:pyplots-db"
      - "--set-secrets=DATABASE_URL=DATABASE_URL:latest"
      - "--set-env-vars=ENVIRONMENT=production"
      - "--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
      - "--set-env-vars=GCS_BUCKET=pyplots-images"
    id: "deploy"
    waitFor: ["push-image"]

  # Report deployed URL
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "services"
      - "describe"
      - "${_SERVICE_NAME}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--format=value(status.url)"
    id: "get-url"
    waitFor: ["deploy"]

# Store image in Artifact Registry
images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s" # 20 minutes
